- pages/_app.tsx
- public/theme/theme.ts
- close #5 
차크라 UI 커스텀 색상 추가
```js
<Button color="hey.main">테스트</Button>
<Button color="hey.darkGray">테스트</Button>
<Button color="hey.sub">테스트</Button>
```
> chore: 차크라 UI 커스텀 색상 추가

- package-lock.json
- package.json
- pages/index.tsx
- close #6 
로그인 집입 페이지 마크업
비회원으로 둘러보기 라는 말이 괜찮은 지 궁금합니다
> feat: 로그인 진입 페이지 마크업

- .eslintrc.json
- components/Header/index.tsx
- components/Stores/index.tsx
- components/Stores/storetitle.tsx
- package-lock.json
- package.json
- pages/_app.tsx
- pages/_document.tsx
- close #18 
제가 템플릿 초반 셋팅을 제대로 못했네요...
린트를 추가합니다.
> chore: eslint 추가 설정

- Licence
> feat: Licence

- .eslintrc.json
- package-lock.json
- package.json
- pages/_app.tsx
- close #26 
- 코드리뷰에서 자주 나타나는 것들을 자동화로 진행합니다.
> chore: eslint airbnb

- .github/workflows/ci-workflow.yml
- package.json
- close #28 
- PR을 올릴 시 자동으로 코드 퀄리티를 체킹합니다.
> feat: GitHub Action CI

- components/Mypage/mypageTitle.tsx
- components/Mypage/post.tsx
- pages/_app.tsx
- pages/_document.tsx
- pages/mypage/orderlist/index.tsx
- close #36 
- 마이페이지 내 주문 리스트 마크업
> feat: 마이페이지(내 주문 리스트) 마크업

- package-lock.json
- package.json
- close #41 
무한스크롤 구현을 위한 npm 설치
> chore: react-intersection-observer 설치

- types/orders.ts
> feat: orders type

- components/Orders/Thread.tsx
- pages/orders/[id].tsx
> feat: thread mark up

- components/Api/getCakeList.ts
- components/Api/getMarketDetail.ts
- components/Api/getMarketList.ts
- components/Api/index.tsx
- components/Main/cakeList.tsx
- components/Market/marketProfile.tsx
- next.config.js
- pages/api/enrollments/[id].tsx
- close #57 
업체 상세페이지와 실제 데이터를 연동한다
실 배포에서 에러없이 작동하는 것을 확인했습니다.
추가적으로 main 페이지의 라우팅 주소를 일부 수정하였습니다
> feat: 업체 상세 페이지를 실제 데이터와 연결한다

- components/Admin/index.tsx
- components/Admin/marketItem.tsx
- components/Admin/marketList.tsx
- components/Api/getMarketList.ts
- components/Api/patchMarketStatus.ts
- components/Market/marketProfile.tsx
- pages/api/enrollments/index.tsx
- pages/api/marketstatus.tsx
- close #62
feat: 업체 승인 리스트의 통신과 구현을 완성한다
1. 현제 권한관련 문제로 삭제기능은 정상작동하나 허가기능은 에러가 발생합니다
(백엔드가 수정되면 문제없음)
2. 마찬가지로 주석처리된 if문 필터의 경우 기존 APPROVED , WAITED만 보여야 하는 탭에서 DELETED도 보여
일부 제거되었습니다.
3. 삭제한 업체를 다시 돌리는 기능은 차후 구현예정임으로 함부로 삭제하면 안됩니다(?)
> feat: 업체 승인 리스트의 통신과 구현을 완성한다

- pages/orders/new.tsx
- close #70 
- 기능 구현 완료
- api 연동 완료
시연 영상 촬영 이후 UX 개선 예정
> feat: 주문 생성

- components/Mypage/enrollmentForm.tsx
- constants/errorMessages.ts
- close #49 
마이페이지(업체 정보 등록) validation 추가
우선 중요한 사업자 등록 번호와 대표자 이름만 추가했고, 
api 연동하면서 더 추가할 예정입니다
> feat: 마이페이지(업체 정보 등록) validation 추가

- components/Header/index.tsx
- components/Main/cakeItem.tsx
- components/Main/cakeList.tsx
- components/Main/constants.ts
- pages/api/orders.tsx
- close #67
메인페이지의 통신과 구현을 완성한다
구현 영상 촬영으로 현재 데이터가 없어 사진을 찍지 못했습니다
> feat: 메인페이지의 통신과 구현을 완성한다

- components/Api/postEnrollment.ts
- components/Mypage/enrollmentForm.tsx
- pages/index.tsx
- close #65 
- 업체 정보 등록 api 연동 완료
성공적으로 등록되면 location에서 marketId를 확인할 수 있습니다.
이후에 등록 완료 페이지 구현할 예정입니다.
> feat: 업체 정보 등록 api

- pages/index.tsx
- close #77 
- '비회원으로 둘러보기' 버튼 클릭 시 메인 페이지 진입 기능 구현
> feat: 비로그인 메인 페이지 진입 기능

- components/Orders/Thread.tsx
- pages/orders/[id].tsx
- types/orders.ts
> feat: thread api 연동

- components/Orders/ImageSlider.tsx
- components/Orders/Thread.tsx
- components/Orders/index.ts
- pages/orders/[id].tsx
- types/orders.ts
- close #80 
- 사진 슬라이더 컴포넌트 개발
- 쓰레드 api 연동
> feat: 상세페이지 사진 개발 및 쓰레드 연동

- components/Admin/index.tsx
- components/Admin/marketItem.tsx
- components/Header/index.tsx
- components/Main/cake/cakeMain.tsx
- components/Main/location/locationListItem.tsx
- close #84 
feat: 반응형 디자인에 따른 UI/UX 수정
> feat: 반응형 디자인에 따른 UI/UX 수정

- components/Orders/ImageSlider.tsx
- components/Orders/Thread.tsx
- pages/orders/[id].tsx
- utils/orders.ts
- close #85 
- 리액트 쿼리 마이그레이션
- 유틸함수 추가 -> 영어에서 한글
- 자잘한 스타일 변경
> feat: 상세페이지 리액트쿼리 마이그레이션 및 유틸함수 개발

- pages/api/users/kakao-login.ts
- pages/index.tsx
- pages/main.tsx
- close #81 
- 카카오 로그인 성공 시
- 인가 코드 발급
- 토큰 생성
- access token 존재 시, 페이지 분기 구현 예정입니다.
> feat: 로그인 성공 시, api 연동

- components/Orders/Thread.tsx
- pages/orders/[id].tsx
- close #92 
- 업체 선택을 개발했어요. api 연동
- 스켈레톤 ui를 적용했어요.
> feat: 업체 선택 개발

- components/Admin/marketItem.tsx
- components/Admin/marketList.tsx
- components/Api/Main.ts
- components/Api/types.ts
- components/Main/cake/cakeList.tsx
- pages/api/enrollments/index.tsx
- pages/api/orders.tsx
- close #53 
메인페이지 , 업체 신청 리스트의 무한 스크롤을 구현한다
React-query의 infinity 스크롤을 통해 구현한다
> feat: 메인페이지 , 업체 신청 리스트 무한스크롤

- .eslintrc.json
- components/Orders/Thread.tsx
- hooks/useSelectOffer.ts
- pages/orders/[id].tsx
- close #97 
- 쓰레드 offer 요청 커스텀훅 개발
- offer 요청 데이터 fix
- eslint spreading props open
> refactor: thread 관심사 분리

- pages/orders/new.tsx
- types/orders.ts
- utils/orders.ts
- close #99 
- 타입 개선
- chakra ui 적극 사용
- 지금 추가 개선 작업에 있어요. 타입적인 부분에서 변화가 많아서 PR 먼저 올려요.
> refactor: 타입 정의 후 chakra ui radio 적용, 주문 생성 페이지

- components/Mypage/enrollmentForm.tsx
- components/Mypage/enrollmentInfo.tsx
- components/Mypage/mypageTitle.tsx
- pages/index.tsx
- pages/mypage/enrollment/index.tsx
- pages/mypage/enrollment/success/index.tsx
- close #74 
- 업체 정보 등록 완료 시, 페이지 구현
- 등록 완료 시, 뒤로가기 버튼 노출 제거
> feat: 업체 정보 등록 완료 페이지 구현

- hooks/useImageUpload.ts
- pages/orders/new.tsx
- close #99 
- 커스텀 훅 개발
- 여러장의 파일 업로드 가능
- 미리보기 지원
- 디자인 추가 예정
> feat: 주문 생성 이미지 드래그앤드랍

- .eslintrc.json
- components/Admin/index.tsx
- components/Admin/marketList.tsx
- components/Header/index.tsx
- components/Layout/layout.tsx
- components/Main/cake/cakeList.tsx
- components/Main/cake/cakeMain.tsx
- pages/_app.tsx
- pages/index.tsx
- pages/orders/new.tsx
- styles/font.css
- close #105 
- 로그인 path 수정
- layout component 추가
- noconsole off
- font 추가
- 옵셔널 방어
- 스타일 수정
- width 수정
> refactor: global 수정

- components/Main/cake/cakeMain.tsx
- components/Main/location/locationSelectBox.tsx
- hooks/useImageUpload.ts
- pages/orders/new.tsx
- public/theme/theme.ts
- types/orders.ts
- close #105 
- 차크라 메인 컬러 변경
- 슬라이더 추가 (가격)
- 슬라이더 최대 100000원 이상 시, 직접 입력 개발
- 사진 최대 3개 개발
- 이미지 미리보기 스타일 변경
- 글자 짤림 현상 해결 (헤더)
> feat: chakra custom 및 new order 사진 제한 개발

- constants/cakeFormat.ts
- pages/orders/new.tsx
- types/orders.ts
- utils/orders.ts
- close #99 
- 기획 변경으로 all 속성 제거
- format 개선 -> 0이 제거안되었는데 이제는 제거가 되어요.
- router를 달았어요.
- 메세지를 같이 보여줘요.
> feat: 주문 추가 디테일 개선

- components/Orders/Thread.tsx
- close #80 
- 이제 쓰레드에서 마켓 이름을 누르면 마켓 정보로 이동해요.
> feat: market page link 연동

- pages/_app.tsx
- styles/style.css
- close #113 
- 스크롤이 생길때 화면 흔들림 현상을 해결해요.
> feat: scrollbar  none

- package-lock.json
- package.json
- utils/getMemberIdFromToken.ts
- close #115 
- 삭제를 개발하기 위해 토큰을 decode하여 memberId를 비교해요.
- decode를 하기 위해 관련 라이브러리를 설치했어요.
- 해당 라이브러리를 통해 작성자 일치여부를 판별하고 수정 삭제를 보여줄 예정이에요.
> feat: decode util func

- constants/cakeFormat.ts
- hooks/useImageUpload.ts
- pages/orders/[id]/index.tsx
- pages/orders/[id]/new-offer.tsx
- pages/orders/new.tsx
- types/orders.ts
- utils/orders.ts
- close #110 
- 오퍼 버튼 추가
- 오퍼 페이지 개발
- 오퍼 api 연동
- 커스텀 훅 수정 (maxlen)
- 기획 반영 (all 제거)
> feat: 오퍼 기능 개발

- pages/orders/[id]/index.tsx
- close #117 
- serversideprops
> refactor: ssr 이용, useQuery remove

- pages/orders/new.tsx
- types/orders.ts
- close #99 
- 기존 요구사항 1줄 -> 여러줄
> style: Input -> textfiled

- components/Mypage/mypageTitle.tsx
- components/Mypage/types.ts
- pages/index.tsx
- pages/mypage/enrollment/index.tsx
- pages/mypage/enrollment/success/index.tsx
- pages/mypage/orderlist/index.tsx
- close #127 
- 린트 에러 수정 (preview 복구)
> fix: 린트 에러 (preview 수정)

- components/Orders/OfferComments.tsx
- components/Orders/Thread.tsx
- types/offer.ts
- close #130 
쓰레드 댓글 리스트 조회
쓰레드 댓글 작성
이미지 추가
댓글 삭제 api 연동
쓰레드 댓글 관련 api 연동
> feat: thread comment

- components/Orders/OfferComments.tsx
- pages/orders/[id]/new-offer.tsx
- pages/orders/new.tsx
- utils/getAccessToken.ts
> feat: 로그인 기능 추가

- components/Orders/ImageSlider.tsx
- components/Orders/OfferComments.tsx
- hooks/useSelectOffer.ts
- pages/orders/[id]/index.tsx
- close #146 
-  댓글 작성 시 placeHolder 에 Enter password 보여짐
-  주문 상세 페이지에서 이미지 잘림
- 업체 선택
> fix: 상세페이지 애러 대응 (ver1)

- components/Header/index.tsx
- utils/deleteAccessToken.ts
- close #144
access_token 기반 해더 변경 (로그인 로그아웃)
> feat: access_token 기반 해더 변경

- pages/index.tsx
- pages/main.tsx
- close #150 
- 로그인 메인 리팩터링
- 401 애러 대응
> fix: 메인 로그인 애러 대응

- components/Header/index.tsx
- utils/deleteAccessToken.ts
- close #149 
- 로그아웃 아이콘 클릭 시, access_token / refresh_token 제거 및 라우팅
- 헤더에서 로그인 진행 시, 마이페이지 아이콘 바로 안보임 에러 해결
> feat: 로그아웃 구현 

- components/Header/index.tsx
> fix: header link

- pages/login.tsx
> fix: login issue

- pages/login.tsx
Reverts prgrms-web-devcourse/team-7sung-heycake-fe#156
> Revert "fix: login issue"

- components/Header/index.tsx
Reverts prgrms-web-devcourse/team-7sung-heycake-fe#154
> Revert "fix: header link"

- components/Api/Enrollment.ts
- components/Market/index.tsx
- pages/index.tsx
- pages/main.tsx
> feat: 지연님 수정사항 + 일부 로딩개선

- components/Mypage/enrollmentForm.tsx
> feat: 업체 등록 api 연동

- components/Mypage/enrollmentForm.tsx
> fix: 토큰 발급 코드 위치 변경

- components/Orders/OfferComments.tsx
- pages/orders/[id]/new-offer.tsx
> feat: error message 연동

- components/Orders/OfferComments.tsx
> fix: field name change

- components/Orders/OfferComments.tsx
> fix: access token

- components/Orders/OfferComments.tsx
> fix: axios -> publicApi

- components/Mypage/post.tsx
- components/Orders/OfferComments.tsx
- pages/mypage/orderlist/index.tsx
> feat: invalidateQueries

- components/Mypage/enrollmentForm.tsx
- close #148 
- 업체 등록 후 재로그인하게 로직을 추가했어요.
> feat: 업체 등록 후 재로그인

- components/Mypage/enrollmentForm.tsx
- pages/mypage/enrollment/index.tsx
- close #137 
- 업체 등록 페이지 스타일링 추가
- 차크라 ui 적용
> refactor: chakra ui (Mypage)

- components/Mypage/post.tsx
- hooks/useSelectOffer.ts
- pages/orders/[id]/new-offer.tsx
- close #148 
- 업체 선택 해결
- null check
- router
> fix: mypage and order

- components/Mypage/enrollmentForm.tsx
- components/Orders/OfferComments.tsx
- hooks/useHandleAxiosError.ts
- hooks/useSelectOffer.ts
- pages/main.tsx
- pages/orders/[id]/new-offer.tsx
- close #178 
- 애러 메세지를 띄우는 것에 대해 커스텀훅을 만들었어요.
- 이제 차크라 UI를 통해 메세지를 보여줘요.
> feat: custom hook (error)

- components/Mypage/enrollmentForm.tsx
- hooks/useSelectOffer.ts
- pages/orders/[id]/new-offer.tsx
- pages/orders/new.tsx
- close #133 
- toast를 적용했어요.
-
> refactor: chakra ui - toast

- components/Mypage/post.tsx
- close #177 
- 예약된 주문 삭제 불가 토스트 적용
위치는 이후 수정될 예정입니다.
> feat: 예약된 주문 삭제 불가 토스트 적용

- components/Orders/CakeSelect.tsx
- hooks/useImageUpload.ts
- pages/_app.tsx
- pages/orders/new.tsx
- close #183 
- 이미지 삭제 기능 추가
- 폰트 추가
- 케이크 추가 스타일 변경
- 주문 정보 등록 스타일 변경
> refactor: order design

- components/Orders/OfferComments.tsx
- components/Orders/Thread.tsx
- pages/orders/[id]/index.tsx
- types/orders.ts
> refactor: thread design change

- .eslintrc.json
- components/Api/Enrollment.ts
- components/Api/Order.ts
- components/Api/index.tsx
- components/Main/index.tsx
- components/Market/kakaoMaps.tsx
- components/Mypage/enrollmentForm.tsx
- components/Mypage/enrollmentInfo.tsx
- components/Mypage/mypageTitle.tsx
- components/Mypage/post.tsx
- components/Orders/OfferComments.tsx
- constants/errorMessages.ts
- hooks/useSelectOffer.ts
- pages/index.tsx
- pages/mypage/enrollment/success/index.tsx
- pages/mypage/index.tsx
- pages/orders/[id]/new-offer.tsx
- pages/orders/[id]/pay/index.tsx
- pages/orders/new.tsx
- utils/deleteAccessToken.ts
- utils/getMemberIdFromToken.ts
- close #134 
- 모든 console을 제거했어요
- 모든 alert을 제거했어요
- alert을 toast로 대체했어요.
- 예외처리를 했어요.
- eslint의 모든 문제를 해결했어요
- 타입스크립트를 활용하여 아직 타입이 적용 안 된 부분에 타입을 추가했어요.
- 로그인 메세지 상수화를 하였고 적용했어요.
-
> refactor: 린트 애러 해결, 애러 문구 상수화 및 타입 적용

- pages/main.tsx
> feat: 로그인 환경변수 추가

- components/Orders/RemoveImageButton.tsx
- pages/orders/[id]/new-offer.tsx
- pages/orders/new.tsx
- close #134 
- 이미지에 삭제 아이콘 추가 및 삭제 기능 연동
- slider 버벅임 이슈 해결
> refactor: new order 버그 수정 및 삭제 기능 추가

- components/Layout/layout.tsx
- components/Orders/Thread.tsx
- pages/index.tsx
- pages/orders/[id]/new-offer.tsx
- pages/orders/new.tsx
- types/orders.ts
- close #134 
- 쓰레드 타입 속성명 변경
- 레이아웃 정렬 해결
- 오더페이지 리팩터링
> fix: thread and layout

- components/Orders/OfferComments.tsx
- types/offer.ts
- utils/formatCommentDate.ts
- close #214 
1분 전이면 방금 전
1시간 전이면 n분 전
1시간 이후면 20xx-xx-xx
> feat: comment format time

- components/Admin/index.tsx
- components/Main/cake/cakeList.tsx
- components/Main/index.tsx
- components/Market/index.tsx
- components/Mypage/post.tsx
- components/Mypage/successModal.tsx
- components/Orders/OfferComments.tsx
- components/Shared/headerTitle.tsx
- hooks/useHandleAxiosError.ts
- hooks/useSelectOffer.ts
- pages/_app.tsx
- pages/mypage/index.tsx
- pages/orders/[id]/index.tsx
- pages/orders/[id]/new-offer.tsx
- pages/orders/[id]/pay/index.tsx
- pages/orders/new.tsx
> refactor: 디자인 & 사용성 반영 1차

- components/Orders/OfferComments.tsx
- pages/orders/[id]/index.tsx
> feat: 2차 배포 전 주문페이지 디테일 개선

- components/Mypage/enrollmentForm.tsx
- components/Mypage/successModal.tsx
> refactor: mypage rollback

- pages/main.tsx
> fix: 로그인 문제 해결

- pages/main.tsx
> chore: ver2.01

- components/Mypage/enrollmentForm.tsx
- components/Mypage/successModal.tsx
- pages/mypage/index.tsx
> fix: 모달 안뜨는 이슈 해결

- components/Mypage/enrollmentForm.tsx
- components/Mypage/post.tsx
- components/Mypage/successModal.tsx
- pages/_app.tsx
- pages/mypage/index.tsx
- pages/mypage/orderlist/index.tsx
- types/orders.ts
- utils/orders.ts
- close #225 
- 내 주문 리스트 오퍼 개수 에러 핸들링
- 자잘한 디자인 수정
> fix: 내 주문 리스트 오퍼 개수

- components/Main/index.tsx
- components/Orders/OfferComments.tsx
- pages/_app.tsx
- pages/orders/[id]/index.tsx
- close #224 
- 댓글 작성 후 댓글 내용 남아있는 문제 해결
- 4초가 지나도 페이지 변경이 안 되면 애러메세지를 띄워주었는데 애러메세지가 뜨면 스피너가 사라지는 것을 발견
- 애러메세지 제거
- eslint 경고 제거를 위해 주석
> fix: comment clear

- pages/mypage/index.tsx
> fix: 문구 중복 해결

- constants/Main.ts
- close #224 
fix: 메인페이지 undefined 변경
> fix: 메인페이지 undefined 변경

- components/Mypage/post.tsx
- pages/mypage/orderlist/index.tsx
- types/orders.ts
- close #236 
- 내 주문 리스트 로직 관련
> refactor: 내 주문 리스트 로직 관련 (마이페이지)
